
public interface Data {

    String DRIVER = "oracle.jdbc.driver.OracleDriver";
    String URL = "jdbc:oracle:thin:@localhost:1521:xe";
    String USER = "HR";
    String PASSWORD = "hr";

    String SQL_NUMBER_OF_EMPLOYEES = "SELECT COUNT(EMPLOYEE_ID)+\n"
            + "FROM DEPARTMENTS, EMPLOYEES\n"
            + "WHERE EMPLOYEES.DEPARTMENT_ID=DEPARTMENTS.DEPARTMENT_ID";

    String SQL_NAME_OF_DEPS = "SELECT DEPARTMENT_NAME FROM DEPARTMENTS, EMPLOYEES\n"
            + "WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID\n"
            + "GROUP BY DEPARTMENT_NAME";

    String SQL_EMPS_DEPS = "SELECT * FROM EMPLOYEES, DEPARTMENTS "
            + "WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID "
            + "ORDER BY EMPLOYEES.LAST_NAME, EMPLOYEES.FIRST_NAME";

    String[] COLUMN_NAME = {"DOLGOZÓ_AZONOSÍTÓ", "KERESZTNÉV", "VEZETÉKNÉV", "E-mail", "Telefonszám", "Belépési dátum", "Foglalkozás"
        + "Fizetés", "VEZETŐ_AZONOSÍTÓ", "RÉSZLEG_NÉV"};

    String SQL_DEPS_ID = "SELECT DEPARTMENT_ID FROM DEPARTMENTS, EMPLOYEES\n"
            + "WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID\n"
            + "GROUP BY DEPARTMENT_NAME";

    String SQL_EMPS_DEPS_DEP = "SELECT * FROM EMPLOYEES, DEPARTMENTS "
            + "WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID AND DEPARTMENT_NAME = ? \n"
            + "ORDER BY EMPLOYEES.LAST_NAME, EMPLOYEES.FIRST_NAME";
}
